### ISSUE TITLE
ValueError: ndarray is not C-contiguous

### ISSUE THREAD

**Issue by mtazzari** [mtazzari/galario#121]
I get this error by calling one of `galario` functions:

```
Traceback (most recent call last):
  File "quickstart_twhya.py", line 169, in <module>
    chi2 = g_double.chi2Profile(np.ones(nxy), Rmin, dR, nxy, dxy, u, v, Re, Im, w)
  File "libcommon.pyx", line 629, in libcommon.chi2Profile
  File "stringsource", line 646, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 347, in View.MemoryView.memoryview.__cinit__
```

**Comment by fredRos** [comment]
Unfortunately the error message doesn't say which input array is not contiguous but that's a cython limitation. We require all array inputs to be contiguous because the underlying C/C++ implementation is agnostic of numpy tricks. The solution is easy. Call

```python
u = numpy.ascontiguousarray(u)
v = numpy.ascontiguousarray(v)
...
```
on all your inputs. You can check manually if an array is contiguous with `u.flags`. Often you will call galario repeatedly in a fit. To avoid making copies again and again, we ask the user to do the conversion if necessary. In fact, `ascontiguousarray(u)` doesn't copy `u` if `u` is already contiguous.
