### ISSUE TITLE
Add license headers to all source files

### ISSUE THREAD

**Issue by mtazzari** [mtazzari/galario#131]
Add license headers to all the source files.

Some ideas:

https://softwareengineering.stackexchange.com/questions/68134/best-existing-license-for-closed-source-code

**Comment by fredRos** [comment]
One basic decision is whether to put our names in directly or not. To be more flexible and allow others to join, here what we use in BAT. I like it because it's concise. We should should then add a file  to the project that lists the developer team

```
/*
 * Copyright (C) 2007-2018, the BAT core developer team
 * All rights reserved.
 *
 * For the licensing terms see doc/COPYING.
 * For documentation see http://mpp.mpg.de/bat
 */
```

And here is a header from EOS that is more verbose but more explicit about who contributed when. What's not good is that it tries to fix the GPL version. We should only say *v3 or later*

```
/*
 * Copyright (c) 2011, 2013-2018 Danny van Dyk
 * Copyright (c) 2011 Frederik Beaujean
 *
 * This file is part of the EOS project. EOS is free software;
 * you can redistribute it and/or modify it under the terms of the GNU General
 * Public License version 2, as published by the Free Software Foundation.
 *
 * EOS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 59 Temple
 * Place, Suite 330, Boston, MA  02111-1307  USA
 */
```
